### ISSUE TITLE
An error occurs when updating PowerToys to version 0.86.

### ISSUE THREAD

**Issue by 0Chan-smc** [patcher454/DeepLTranslatorPowerToys#5]
I've been using the 0.82 version with the API key connected and working fine. After updating to 0.86, I'm getting an "UNK -> UNK error occurs".

The API key hasn't changed, but the problem occurs after the update.

To solve this, I deleted the existing DeepLTranslator and updated plugin to v1.0.2, but it doesn't seem to be recognized correctly.

Do I need to uninstall and reinstall PowerToys to fix the problem?

**Comment by 0Chan-smc** [comment]
Never mind. The problem is solved.

**Comment by patcher454** [comment]
Hi @0Chan-smc
Glad to hear that the issue has been resolved.
If you don't mind, could you let me know what the issue was and how you resolved it?

**Comment by 0Chan-smc** [comment]
@patcher454  Sure. The problem was 'UNK -> UNK error' after  I updated the PowerToys version to 0.86, but left the plugin version unchanged.

Unfortunately, I don't know how I fixed, it came back to normal after a day.
So maybe it can be deepL API server issue.

By the way thank you so much for creating such a useful plugin, I'm enjoying using it.
